// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asprule1020.DataAccess.Data;

#nullable disable

namespace asprule1020.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260208120537_UpdateProvDistIdType")]
    partial class UpdateProvDistIdType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("asprule1020.Models.PhBarangay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("barangay");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_municipality");

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("ProvinceDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_district");

                    b.Property<string>("PsgcBgy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_bgy");

                    b.Property<string>("PsgcCityMun")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_citymun");

                    b.Property<string>("PsgcProvDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_provdist");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("PsgcSubMun")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_submun");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("SubMunicipality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("submunicipality");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_bgy");
                });

            modelBuilder.Entity("asprule1020.Models.PhCityMun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_municipality");

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("ProvinceDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_district");

                    b.Property<string>("PsgcCityMun")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_citymun");

                    b.Property<string>("PsgcProvDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_provdist");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_citymun");
                });

            modelBuilder.Entity("asprule1020.Models.PhProvDist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("ProvinceDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_district");

                    b.Property<string>("PsgcProvDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_provdist");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_provdist");
                });

            modelBuilder.Entity("asprule1020.Models.PhRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shortname");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_reg");
                });

            modelBuilder.Entity("asprule1020.Models.Register", b =>
                {
                    b.Property<string>("transId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("estBisPermitDateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("estBisPermitFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estBisPermitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("estBisPermitValidityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("estBrgy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estBusinessNature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estChemSubstance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estCityMun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estCurrentCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("estEmailApprovedSentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("estEmailReapplicationSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("estEvalAssinged")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("estEvalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("estEvalEmailSendStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estEvalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estEvalRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estFemaleCount")
                        .HasColumnType("int");

                    b.Property<bool>("estIsEmailApprovedSent")
                        .HasColumnType("bit");

                    b.Property<bool>("estIsEmailReapplicationSent")
                        .HasColumnType("bit");

                    b.Property<bool>("estIsUpdating")
                        .HasColumnType("bit");

                    b.Property<string>("estLegalOrg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estLegalOrgOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estMaleCount")
                        .HasColumnType("int");

                    b.Property<string>("estName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estOtherBusNature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("estOwnerFirst")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("estOwnerLast")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("estOwnerMid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("estOwnerValidIDDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("estOwnerValidIDDateExpire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("estOwnerValidIDDateIssued")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<string>("estOwnerValidIDFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estOwnerValidIDNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("estPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("estPoHeadEvalDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estPoHeadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estPoHeadRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estReasonForUpdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("estRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("estReopeningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("estSECDateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("estSECFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estSECNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("estStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estStreet")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.PrimitiveCollection<string>("estTechInfo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estTechInfo1Other")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("estTechInfo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estTechInfo2Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estTotalAssets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estTotalEmployees")
                        .HasColumnType("int");

                    b.Property<string>("estType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rule1020Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("transId");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
