// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asprule1020.DataAccess.Data;

#nullable disable

namespace asprule1020.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328034249_AddEvaluationChkListAndRemarksToDb")]
    partial class AddEvaluationChkListAndRemarksToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("asprule1020.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EstProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RegisterId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("asprule1020.Models.BranchUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Rule1020Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId");

                    b.ToTable("BranchUnits");
                });

            modelBuilder.Entity("asprule1020.Models.EvaluationChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("est_adress_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_barangay_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_bnature_oth_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_bperm_dateiss_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_bperm_number_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_bperm_validity_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_bus_nature_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_bus_perm_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_chemsub_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_citymun_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_contact_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_cur_cap_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_email_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_femalenum_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_legalorg_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_malenum_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_manag_first_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_manag_last_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_manag_mid_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_name_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_peza_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_province_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_regdate_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_region_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_sec_dateiss_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_sec_number_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_sec_permit_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_techinfo1_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_techinfo2_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_techinfooth1_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_techinfooth2_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_termrep_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_tin_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_total_asset_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_totalemploy_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_type_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_valid_dateiss_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_valid_number_ck")
                        .HasColumnType("bit");

                    b.Property<bool>("est_valid_validity_ck")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId");

                    b.ToTable("EvaluationChecklists");
                });

            modelBuilder.Entity("asprule1020.Models.EvaluationRemarks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("est_adress_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_barangay_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_bnature_oth_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_bperm_dateiss_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_bperm_number_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_bperm_validity_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_bus_nature_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_bus_perm_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_chemsub_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_citymun_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_contact_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_cur_cap_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_email_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_femalenum_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_legalorg_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_malenum_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_manag_first_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_manag_last_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_manag_mid_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_name_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_peza_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_province_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_regdate_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_region_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_sec_dateiss_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_sec_number_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_sec_permit_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_techinfo1_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_techinfo2_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_techinfooth1_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_techinfooth2_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_termrep_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_tin_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_total_asset_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_totalemploy_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_type_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_valid_dateiss_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_valid_number_input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("est_valid_validity_input")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId");

                    b.ToTable("EvaluationRemarks");
                });

            modelBuilder.Entity("asprule1020.Models.LaborUnion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RegisterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnionAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnionBLR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnionName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegisterId");

                    b.ToTable("LaborUnions");
                });

            modelBuilder.Entity("asprule1020.Models.PhBarangay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("barangay");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_municipality");

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("ProvinceDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_district");

                    b.Property<string>("PsgcBgy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_bgy");

                    b.Property<string>("PsgcCityMun")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_citymun");

                    b.Property<string>("PsgcProvDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_provdist");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("PsgcSubMun")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_submun");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("SubMunicipality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("submunicipality");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_bgy");
                });

            modelBuilder.Entity("asprule1020.Models.PhCityMun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_municipality");

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("ProvinceDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_district");

                    b.Property<string>("PsgcCityMun")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_citymun");

                    b.Property<string>("PsgcProvDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_provdist");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_citymun");
                });

            modelBuilder.Entity("asprule1020.Models.PhProvDist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("ProvinceDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_district");

                    b.Property<string>("PsgcProvDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_provdist");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_provdist");
                });

            modelBuilder.Entity("asprule1020.Models.PhRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shortname");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_reg");
                });

            modelBuilder.Entity("asprule1020.Models.Register", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EstBisPermitDateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstBisPermitFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstBisPermitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EstBisPermitValidityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstBrgy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstBusinessNature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstChemSubstance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstCityMun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstCurrentCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EstEmailApprovedSentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstEmailReapplicationSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstEvalAssinged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EstEvalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstEvalEmailSendStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstEvalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstEvalRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstFemaleCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstFiledClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("EstIsEmailApprovedSent")
                        .HasColumnType("bit");

                    b.Property<bool?>("EstIsEmailReapplicationSent")
                        .HasColumnType("bit");

                    b.Property<bool>("EstIsPeza")
                        .HasColumnType("bit");

                    b.Property<bool?>("EstIsUpdating")
                        .HasColumnType("bit");

                    b.Property<string>("EstLegalOrg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstLegalOrgOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstMaleCount")
                        .HasColumnType("int");

                    b.Property<string>("EstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstOtherBusNature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstOwnerFirst")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstOwnerLast")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstOwnerMid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EstOwnerValidIDDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstOwnerValidIDDateExpire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstOwnerValidIDDateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstOwnerValidIDFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstOwnerValidIDNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("EstPoHeadEvalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstPoHeadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstPoHeadRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstReasonForUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EstRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstReopeningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstSECDateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstSECFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstSECNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstTaxIdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("EstTechInfo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstTechInfo1Other")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("EstTechInfo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstTechInfo2Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstTotalAssets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstTotalEmployees")
                        .HasColumnType("int");

                    b.Property<string>("EstType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Rule1020Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Registers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("asprule1020.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("asprule1020.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asprule1020.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("asprule1020.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("asprule1020.Models.ApplicationUser", b =>
                {
                    b.HasOne("asprule1020.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("asprule1020.Models.BranchUnit", b =>
                {
                    b.HasOne("asprule1020.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("asprule1020.Models.EvaluationChecklist", b =>
                {
                    b.HasOne("asprule1020.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("asprule1020.Models.EvaluationRemarks", b =>
                {
                    b.HasOne("asprule1020.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("asprule1020.Models.LaborUnion", b =>
                {
                    b.HasOne("asprule1020.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId");

                    b.Navigation("Register");
                });
#pragma warning restore 612, 618
        }
    }
}
