// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asprule1020.DataAccess.Data;

#nullable disable

namespace asprule1020.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260212133156_AddApplicationUserToDb")]
    partial class AddApplicationUserToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("asprule1020.Models.PhBarangay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barangay")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("barangay");

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_municipality");

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("ProvinceDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_district");

                    b.Property<string>("PsgcBgy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_bgy");

                    b.Property<string>("PsgcCityMun")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_citymun");

                    b.Property<string>("PsgcProvDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_provdist");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("PsgcSubMun")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_submun");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("SubMunicipality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("submunicipality");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_bgy");
                });

            modelBuilder.Entity("asprule1020.Models.PhCityMun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityMunicipality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city_municipality");

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("ProvinceDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_district");

                    b.Property<string>("PsgcCityMun")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_citymun");

                    b.Property<string>("PsgcProvDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_provdist");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_citymun");
                });

            modelBuilder.Entity("asprule1020.Models.PhProvDist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("ProvinceDistrict")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("province_district");

                    b.Property<string>("PsgcProvDist")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_provdist");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_provdist");
                });

            modelBuilder.Entity("asprule1020.Models.PhRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GeographicLevel")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("geographic_level");

                    b.Property<string>("OldName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_name");

                    b.Property<string>("PsgcReg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("psgc_reg");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("region");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("shortname");

                    b.HasKey("Id");

                    b.ToTable("tbl_psgc_reg");
                });

            modelBuilder.Entity("asprule1020.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("EstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegisterId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("RegisterId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("asprule1020.Models.Register", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime?>("EstBisPermitDateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstBisPermitFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstBisPermitNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EstBisPermitValidityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstBrgy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstBusinessNature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstChemSubstance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstCityMun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstCurrentCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EstEmailApprovedSentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstEmailReapplicationSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstEvalAssinged")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EstEvalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstEvalEmailSendStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstEvalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstEvalRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstFemaleCount")
                        .HasColumnType("int");

                    b.Property<bool>("EstIsEmailApprovedSent")
                        .HasColumnType("bit");

                    b.Property<bool>("EstIsEmailReapplicationSent")
                        .HasColumnType("bit");

                    b.Property<bool>("EstIsUpdating")
                        .HasColumnType("bit");

                    b.Property<string>("EstLegalOrg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstLegalOrgOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstMaleCount")
                        .HasColumnType("int");

                    b.Property<string>("EstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstOtherBusNature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstOwnerFirst")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstOwnerLast")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstOwnerMid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EstOwnerValidIDDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstOwnerValidIDDateExpire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EstOwnerValidIDDateIssued")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<string>("EstOwnerValidIDFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstOwnerValidIDNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstPhone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("EstPoHeadEvalDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstPoHeadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstPoHeadRemarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstProvince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstReasonForUpdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EstRegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstReopeningDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstSECDateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstSECFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstSECNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("EstTechInfo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstTechInfo1Other")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("EstTechInfo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstTechInfo2Other")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstTotalAssets")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstTotalEmployees")
                        .HasColumnType("int");

                    b.Property<string>("EstType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rule1020Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.ToTable("AspNetUsers", t =>
                        {
                            t.Property("EstName")
                                .HasColumnName("Register_EstName");

                            t.Property("EstProvince")
                                .HasColumnName("Register_EstProvince");
                        });

                    b.HasDiscriminator().HasValue("Register");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("asprule1020.Models.ApplicationUser", b =>
                {
                    b.HasOne("asprule1020.Models.Register", "Register")
                        .WithMany()
                        .HasForeignKey("RegisterId");

                    b.Navigation("Register");
                });
#pragma warning restore 612, 618
        }
    }
}
